apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rtpengine-daemonSet
  labels:
    app.kubernetes.io/name: rtpengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rtpengine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rtpengine
    spec:
      containers:
      - name: ng-control
        image: PCH-rtpengine:v5.1
        ports:
        - containerPort: 2223
---
apiVersion: v1
kind: Service
metadata:
  name: rtpengine
spec:
  selector:
    app.kubernetes.io/name: rtpengine
  clusterIP: None
---


