
apiVersion: v1
kind: Service
metadata:
  name: rtpengine-10.22.149.230-p0
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-10.22.149.230"
spec:
  type: LoadBalancer
  selector:
    ip: 10.22.149.230
    partition-leader-0: "True"
  ports:
    - name: rtp-20000
      protocol: UDP
      port: 20000
      targetPort: 20000
    - name: rtp-20001
      protocol: UDP
      port: 20001
      targetPort: 20001
    - name: rtp-20002
      protocol: UDP
      port: 20002
      targetPort: 20002
    - name: rtp-20003
      protocol: UDP
      port: 20003
      targetPort: 20003
    - name: rtp-20004
      protocol: UDP
      port: 20004
      targetPort: 20004
    - name: rtp-20005
      protocol: UDP
      port: 20005
      targetPort: 20005
    - name: rtp-20006
      protocol: UDP
      port: 20006
      targetPort: 20006
    - name: rtp-20007
      protocol: UDP
      port: 20007
      targetPort: 20007
    - name: rtp-20008
      protocol: UDP
      port: 20008
      targetPort: 20008
    - name: rtp-20009
      protocol: UDP
      port: 20009
      targetPort: 20009
    - name: rtp-20010
      protocol: UDP
      port: 20010
      targetPort: 20010
    - name: rtp-20011
      protocol: UDP
      port: 20011
      targetPort: 20011
    - name: rtp-20012
      protocol: UDP
      port: 20012
      targetPort: 20012
    - name: rtp-20013
      protocol: UDP
      port: 20013
      targetPort: 20013
    - name: rtp-20014
      protocol: UDP
      port: 20014
      targetPort: 20014
    - name: rtp-20015
      protocol: UDP
      port: 20015
      targetPort: 20015
    - name: rtp-20016
      protocol: UDP
      port: 20016
      targetPort: 20016
    - name: rtp-20017
      protocol: UDP
      port: 20017
      targetPort: 20017
    - name: rtp-20018
      protocol: UDP
      port: 20018
      targetPort: 20018
    - name: rtp-20019
      protocol: UDP
      port: 20019
      targetPort: 20019

