
apiVersion: v1
kind: Service
metadata:
  name: rtpengine-10-22-149-230-p0
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-10.22.149.230"
spec:
  type: LoadBalancer
  selector:
    ip: 10.22.149.230
    rtpengine-10.22.149.230-p0: "True"
  ports:
    - name: rtp-20000
      protocol: UDP
      port: 20000
      targetPort: 20000

---

apiVersion: v1
kind: Service
metadata:
  name: rtpengine-10-22-149-230-p1
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-10.22.149.230"
spec:
  type: LoadBalancer
  selector:
    ip: 10.22.149.230
    rtpengine-10.22.149.230-p1: "True"
  ports:
    - name: rtp-20001
      protocol: UDP
      port: 20001
      targetPort: 20001

---

apiVersion: v1
kind: Service
metadata:
  name: rtpengine-10-22-149-230-p2
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-10.22.149.230"
spec:
  type: LoadBalancer
  selector:
    ip: 10.22.149.230
    rtpengine-10.22.149.230-p2: "True"
  ports:
    - name: rtp-20002
      protocol: UDP
      port: 20002
      targetPort: 20002

---
